source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'MyFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MyFramework
  pod 'ACPCore', '~> 2.0'

end
